repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: detect-private-key
    -   id: mixed-line-ending

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.3
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
        args: [--strict]
        files: ^obsyncit/

-   repo: https://github.com/pycqa/pylint
    rev: v3.1.0
    hooks:
    -   id: pylint
        args: [--rcfile=pyproject.toml]
        files: ^obsyncit/
