[general]
settings_dir = ".obsidian"
backup_count = 5

[logging]
log_dir = "logs"
rotation = "1 week"
retention = "3 months"
compression = "zip"
level = "INFO"
format = "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"

[sync]
core_settings_files = [
    "appearance.json",
    "app.json",
    "core-plugins.json",
    "community-plugins.json",
    "hotkeys.json"
]

settings_dirs = [
    "plugins",
    "themes",
    "snippets"
] 